name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@22d80fd43684020a74d073b9422ee078f13ba97f
        with:
          inputPath: "manifests"
          outputPath: "output"
          version: "0.0.1"
