name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@78637dbbec482756954f27f262b8b737a8f9a553
        with:
          inputPath: "manifests"
          outputPath: "output"
          repository: "${{ github.event.repository.name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
