name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@c221fef3dc2efc4ea36caf3fbc2d8d11b474c0f1
        with:
          inputPath: "manifests"
          outputPath: "output"
          repository: "${{ github.actor}}/${{ github.event.repository.name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
