name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@b051c88d368b7c0b3110e6f655ee7d3fdb64210e
        with:
          inputPath: "manifests"
          outputPath: "output"
          version: "0.0.1"
