name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@4fa3b424507fd19661ada8080cee026d1e6e6248
        with:
          inputPath: "manifests"
          outputPath: "output"
          repository: "${{ github.actor}}/${{ github.event.repository.name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          bump: "patch"
