name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@079e815a2a85ca5903c8d01e73d033ef2f697e1e
        with:
          inputPath: "manifests"
          outputPath: "output"
          repository: "${{ github.actor}}/${{ github.event.repository.name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          bump: "patch"
