name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@6aeb28223fc964ff8939d43e305096aca0b831ad
        with:
          inputPath: "manifests"
          outputPath: "output"
          version: "0.0.1"
