name: Run Keptn App Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: thschue/keptn-config-generator@b48dd4f2ae343ec4ec555740d6a047e1e4c7667a
        with:
          inputPath: "/github/workspace/manifests"
          outputPath: "/github/workspace/output"
          version: "0.0.1"
